name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint:nofix
      - name: Build and Publish Release
        run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

# https://sergiodxa.com/articles/github-actions-npm-publish
